### ISSUE TITLE
Deprecation warning in debug mode

### ISSUE THREAD

**Issue by mcube27** [wallee-payment/prestashop-mailhook#1]
In debug mode, if I go in : Backoffice/index.php/configure/advanced/emails

I get this error form this module :
Warning: Declaration of Mail::Send($id_lang, $template, $subject, $template_vars, $to, $to_name = NULL, $from = NULL, $from_name = NULL, $file_attachment = NULL, $mode_smtp = NULL, $template_path = _PS_MAIL_DIR_, $die = false, $id_shop = NULL, $bcc = NULL, $reply_to = NULL) should be compatible with MailCore::send($idLang, $template, $subject, $templateVars, $to, $toName = NULL, $from = NULL, $fromName = NULL, $fileAttachment = NULL, $mode_smtp = NULL, $templatePath = _PS_MAIL_DIR_, $die = false, $idShop = NULL, $bcc = NULL, $replyTo = NULL, $replyToName = NULL)

Looks like the $replyToName is missing.

Using Prestashop 1.7.6.4 and php 7.1

**Comment by thomashunziker** [comment]
Thank you for bringing this to our attention. The issue has been addressed in the lastest version.

**Comment by mcube27** [comment]
Hi, 
I installed the v1.1 but now I get this when going to Backoffice/index.php/configure/advanced/emails in debug mode :
Backoffice/index.php/configure/advanced/emails
![image](https://user-images.githubusercontent.com/10844608/78567849-93f85200-7821-11ea-8816-bf73843fd71c.png)

**Comment by mcube27** [comment]
It looks ok, some file named Mail.php was in the override/classes, I don't know how it got there.

Thanks

**Comment by thomashunziker** [comment]
I have updated the readme file to point this fact out. This is a bit of an issue. However it seems that all Prestashop modules are affect by this.
