### ISSUE TITLE
Fatal error Prestashop 1.7.7.8

### ISSUE THREAD

**Issue by Robin-E-Still** [wallee-payment/prestashop-mailhook#2]
Parse error: syntax error, unexpected '*', expecting function (T_FUNCTION) or const (T_CONST)

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

**Comment by Robin-E-Still** [comment]
mailhook has a wrong override

**Comment by Robin-E-Still** [comment]
Edit the Mail.php file inside /web/override/classes

Around line 24 (if I remember correctly) there is a comment that has no opening.
Just put /* in the line above

**Comment by lmeyer1** [comment]
@Robin-E-Still 
What version of file `Mail.php` are you talking about ? No such comment exists in any file version in this repo.

**Comment by alberto-wallee** [comment]
Hi @Robin-E-Still , this error has been fixed in the release 1.2.

**Comment by lmeyer1** [comment]
@Robin-E-Still @alberto-wallee 
Well done! I did not wait 11 months. We no longer use your solutions, because of the way you (don't) treat bugs.
We lost hours and days with your solution, with no helpful reaction of your side during several months 😠 😭
