### ISSUE TITLE
PDF Invoice

### ISSUE THREAD

**Issue by sined123321** [wallee-payment/prestashop-mailhook#4]
Hi there

To install Postfinance Checkout I had to install also this module. The installation of this Module and the Postfinance worked well, but when I order a Product the PDF Invoice isn't attached to the order_conf mail. I also had a Module to attach terms and conditions pdf to another E-Mail template. But this also doesn't work anymore. What can I do, to use both modules and also what can I do that the automatic pdf invoice is attached when the checkbox in prestashop is activated?

Thanks

**Comment by theodorspringwallee** [comment]
Dear [sined123321](https://github.com/sined123321)

Since this seems to be a support case, please get in touch with the PF support: https://www.postfinance.ch/de/support/hotline.html

Best regards
